task:
    # Basic metadata:
    name: Docker Build Push
    only_if: true

    # The build machine:
    osx_instance:
        image: big-sur-base

    # Environment variables:
    env:
        DOCKER_USERNAME: lumine
        DOCKER_PASSWORD: Binnic123!

    # Instructions:
    Docker_Install_Script: brew cask install docker
    Docker_Login_script: docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" quay.io
    Build_Image_script: docker build -t quay.io/lumine/ptero-images:test-egg ./Dockerfiles/Test-CI-Egg
    Push_Image_script: docker push quay.io/lumine/ptero-images:test-egg
