task:
    # Basic metadata:
    name: Docker Build Push
    only_if: true

    # The build machine:
    container:
        image: docker:dind

    # Environment variables:
    env:
        DOCKER_USERNAME: lumine
        DOCKER_PASSWORD: Binnic123!

    # Instructions:
    Docker_Login_script: docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" quay.io
    Build_Image_script: docker build -f Dockerfiles/Test-CI-Egg/Dockerfile -t quay.io/lumine/ptero-images:test-egg .
    Push_Images_script: docker push quay.io/lumine/ptero-images:test-egg
